name: Build NUT

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            --build-arg NUT_VERSION=2.8.5 \
            -t nut:2.8.5 \
            .
